import os
from dotenv import load_dotenv

load_dotenv()

# BOT CREDENTIALS PROVIDED BY BOT FATHER
BOT_USERNAME: str = os.getenv('BOT_USERNAME')
BOT_TOKEN: str = os.getenv('BOT_TOKEN')

# KIWI CREDENTIALS  FLIGHT API
KIWI_API_KEY: str = os.getenv('KIWI_API_KEY')

# DATABASE FILES
DATABASE_PATH = 'database\database.db'

# USER TYPES
ADMINISTRATOR = 'ADMIN'
MODERATOR = 'MODERATOR'
REGULAR_USER = 'REGULAR_USER'

# JOB SCHEDULING INTERVALS - SECONDS
FIRST_RUN_FS = 900
JOB_INTERVAL_FS = 10800

# FLIGHT TRACKING LIMITS
FT_LIMIT = 2
