name: Telegram Bot Test

on:
  pull_request:
    branches: -main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /TELEGRAM-BOT/

    strategy:
      matrix:
        python-version: [3.11]

    env:
      BOT_USERNAME: ${{secrets.GITHUB_TOKEN}}
      BOT_TOKEN: ${{secrets.GITHUB_TOKEN}}
      FIRST_RUN_FS: ${{secrets.GITHUB_TOKEN}}
      JOB_INTERVAL_FS: ${{secrets.GITHUB_TOKEN}}
      FT_LIMIT: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Test Bot Code
        run: python ./bot.py
